import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import HealthWatcher from "@/components/common/ServerDown";
import GlobalMessage from "@/components/common/GlobalMessage";
import Loader from "@/components/common/Loader";
import { ReduxProvider } from "@/store/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Header />
          <div className="min-h-screen flex flex-col">{children}</div>
          <HealthWatcher />
          <Footer />
          <GlobalMessage />
          <Loader />
        </ReduxProvider>
      </body>
    </html>
  );
}
